analyzer:
  # enable-experiment:
  #  - macros
  errors:
    no_leading_underscores_for_local_identifiers: ignore
    prefer_const_constructors: ignore
    deprecated_member_use: ignore
    prefer_const_literals_to_create_immutables: ignore
    avoid_print: ignore
include: package:flutter_lints/flutter.yaml
