name: eye
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  states_rebuilder: ^6.4.0
  flex_color_scheme: ^7.3.1
  package_info_plus: ^8.0.0
  uuid: ^4.4.0
  flutter_lints: ^5.0.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  manager:
    path: D://adn//apps//manager
  flutter_native_splash: ^2.4.2
flutter:
  uses-material-design: true
dev_dependencies:
  build_runner: ^2.1.11
