import 'question.dart';

Iterable<Question> sampleQuestions = [
  Question(
      id: 1,
      category: Category(),
      statement: "What is the main cause of blindness worldwide?",
      a: "Cataract",
      b: "Glaucoma",
      c: "Diabetes",
      d: "Age-related macular degeneration",
      answer: "Cataract",
      explanation: "Cataracts are the leading cause of blindness globally."),
  Question(
      id: 2,
      category: Category(),
      statement: "What is the primary symptom of glaucoma?",
      a: "Headache",
      b: "Eye pain",
      c: "Blurred vision",
      d: "No symptoms",
      answer: "No symptoms",
      explanation: "Glaucoma often has no early symptoms."),
  Question(
      id: 3,
      category: Category(),
      statement: "Which part of the eye is affected by macular degeneration?",
      a: "Cornea",
      b: "Lens",
      c: "Retina",
      d: "Optic nerve",
      answer: "Retina",
      explanation: "Macular degeneration affects the retina."),
  Question(
      id: 4,
      category: Category(),
      statement: "What condition is characterized by increased intraocular pressure?",
      a: "Glaucoma",
      b: "Cataract",
      c: "Myopia",
      d: "Hyperopia",
      answer: "Glaucoma",
      explanation: "Glaucoma is characterized by increased intraocular pressure."),
  Question(
      id: 5,
      category: Category(),
      statement: "What is the standard treatment for a corneal ulcer?",
      a: "Antibiotic drops",
      b: "Warm compress",
      c: "Eyeglasses",
      d: "Eye patch",
      answer: "Antibiotic drops",
      explanation: "Antibiotic drops are commonly used to treat corneal ulcers."),
  Question(
      id: 6,
      category: Category(),
      statement: "What is the common cause of red-eye?",
      a: "Conjunctivitis",
      b: "Glaucoma",
      c: "Cataract",
      d: "Myopia",
      answer: "Conjunctivitis",
      explanation: "Conjunctivitis is a common cause of red-eye."),
  Question(
      id: 7,
      category: Category(),
      statement: "What eye condition is treated with laser photocoagulation?",
      a: "Diabetic retinopathy",
      b: "Cataract",
      c: "Macular degeneration",
      d: "Retinal detachment",
      answer: "Diabetic retinopathy",
      explanation: "Diabetic retinopathy is often treated with laser photocoagulation."),
  Question(
      id: 8,
      category: Category(),
      statement: "What is the leading cause of irreversible blindness in older adults?",
      a: "Macular degeneration",
      b: "Cataract",
      c: "Glaucoma",
      d: "Diabetes",
      answer: "Macular degeneration",
      explanation:
          "Age-related macular degeneration is the leading cause of irreversible blindness in older adults."),
  Question(
      id: 9,
      category: Category(),
      statement: "What symptom is associated with retinal detachment?",
      a: "Flashes of light",
      b: "Red-eye",
      c: "Blurred vision",
      d: "Eye pain",
      answer: "Flashes of light",
      explanation: "Flashes of light are a common symptom of retinal detachment."),
  Question(
      id: 10,
      category: Category(),
      statement: "Which eye condition is often associated with aging?",
      a: "Cataract",
      b: "Myopia",
      c: "Hyperopia",
      d: "Astigmatism",
      answer: "Cataract",
      explanation: "Cataracts are often associated with aging."),
  Question(
      id: 11,
      category: Category(),
      statement: "What is a common symptom of cataracts?",
      a: "Blurred vision",
      b: "Eye pain",
      c: "Red-eye",
      d: "Itching",
      answer: "Blurred vision",
      explanation: "Blurred vision is a common symptom of cataracts."),
  Question(
      id: 12,
      category: Category(),
      statement: "What condition is commonly known as pink eye?",
      a: "Conjunctivitis",
      b: "Glaucoma",
      c: "Cataract",
      d: "Retinopathy",
      answer: "Conjunctivitis",
      explanation: "Conjunctivitis is commonly known as pink eye."),
  Question(
      id: 13,
      category: Category(),
      statement: "What tool is used to measure intraocular pressure?",
      a: "Tonometer",
      b: "Ophthalmoscope",
      c: "Slit lamp",
      d: "Retinoscope",
      answer: "Tonometer",
      explanation: "A tonometer is used to measure intraocular pressure."),
  Question(
      id: 14,
      category: Category(),
      statement: "What is the main symptom of dry eye syndrome?",
      a: "Itching",
      b: "Tearing",
      c: "Dryness",
      d: "Redness",
      answer: "Dryness",
      explanation: "Dryness is the main symptom of dry eye syndrome."),
  Question(
      id: 15,
      category: Category(),
      statement: "What eye condition is characterized by clouding of the lens?",
      a: "Cataract",
      b: "Glaucoma",
      c: "Myopia",
      d: "Astigmatism",
      answer: "Cataract",
      explanation: "Cataracts are characterized by clouding of the lens."),
  Question(
      id: 16,
      category: Category(),
      statement: "What is the primary treatment for bacterial conjunctivitis?",
      a: "Antibiotic drops",
      b: "Steroid drops",
      c: "Warm compress",
      d: "Cold compress",
      answer: "Antibiotic drops",
      explanation: "Antibiotic drops are commonly used to treat bacterial conjunctivitis."),
  Question(
      id: 17,
      category: Category(),
      statement: "What condition causes a shadow or curtain effect in vision?",
      a: "Retinal detachment",
      b: "Cataract",
      c: "Glaucoma",
      d: "Myopia",
      answer: "Retinal detachment",
      explanation: "A shadow or curtain effect in vision is a symptom of retinal detachment."),
  Question(
      id: 18,
      category: Category(),
      statement: "What part of the eye is affected by uveitis?",
      a: "Uvea",
      b: "Cornea",
      c: "Lens",
      d: "Retina",
      answer: "Uvea",
      explanation: "Uveitis is an inflammation of the uvea."),
  Question(
      id: 19,
      category: Category(),
      statement: "What is the primary symptom of blepharitis?",
      a: "Eyelid inflammation",
      b: "Eye pain",
      c: "Blurred vision",
      d: "Red-eye",
      answer: "Eyelid inflammation",
      explanation: "Eyelid inflammation is the primary symptom of blepharitis."),
  Question(
      id: 20,
      category: Category(),
      statement: "What condition is known as lazy eye?",
      a: "Amblyopia",
      b: "Strabismus",
      c: "Myopia",
      d: "Hyperopia",
      answer: "Amblyopia",
      explanation: "Amblyopia is commonly known as lazy eye."),
];
